### ISSUE TITLE
Can't run operator locally

### ISSUE THREAD

**Issue by Kevin-Mok** [Kevin-Mok/kogito-cloud-operator#1]
I can't seem to run [my operator](https://quay.io/repository/kmok/kogito-operator?tab=tags) locally despite it seeming to run fine on AWS. I am running the operator locally in two ways, and both seem to fail to run for similar reasons.

### `oc create`
When running the operator with the following commands:

```sh
oc create -f deploy/service_account.yaml
oc create -f deploy/role.yaml
oc create -f deploy/role_binding.yaml
oc create -f deploy/operator.yaml
```

The events from `oc describe` ([full log](https://github.com/Kevin-Mok/kogito-cloud-operator/files/4698417/describe.log)) indicate that the container is constantly crashing and backing off from restarting as such:
```
Events:
  Type     Reason     Age                    From                         Message
  ----     ------     ----                   ----                         -------
  Normal   Scheduled  40m                   default-scheduler            Successfully assigned kogito-operator-local-4/kogito-operator-598ff5d875-fdh9x to crc-dv9sm-master-0
  Normal   Created    37m (x5 over 40m)     kubelet, crc-dv9sm-master-0  Created container kogito-cloud-operator
  Normal   Started    37m (x5 over 40m)     kubelet, crc-dv9sm-master-0  Started container kogito-cloud-operator
  Normal   Pulled     5m36s (x12 over 40m)  kubelet, crc-dv9sm-master-0  Container image "quay.io/kmok/kogito-operator" already present on machine
  Warning  BackOff    33s (x164 over 39m)   kubelet, crc-dv9sm-master-0  Back-off restarting failed container
```

Then, `oc logs` ([full log](https://github.com/Kevin-Mok/kogito-cloud-operator/files/4698426/pod.log)) seem to indicate some problem with `KogitoRuntime` being missing:
```
{"level":"error","T":"2020-05-28T21:45:52.547Z","logger":"cmd","msg":"no matches for kind \"KogitoRuntime\" in version \"app.kiegroup.org/v1alpha1\"Manager exited non-zero"}
```

### `operator-sdk run --local`
When running the operator locally with `operator-sdk` [as described in the README](https://github.com/kiegroup/kogito-cloud-operator#running-the-kogito-operator-locally), there seems to be a similar error with `KogitoRuntime` being missing:
```
2020-05-28T17:15:45.580-0400	ERROR	cmd	no matches for kind "KogitoRuntime" in version "app.kiegroup.org/v1alpha1"Manager exited non-zero
```
[Full log](https://github.com/Kevin-Mok/kogito-cloud-operator/files/4698444/sdk.log)

When I deploy the same operator on AWS using the `oc create` method, I don't run into this problem at all.

**Comment by Kevin-Mok** [comment]
I thought of ensuring that there's a runtime image with `kogito deploy-service --image-runtime quay.io/kiegroup/kogito-quarkus-jvm-ubi8`, but I'm getting this error when running the command:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/kiegroup/kogito-cloud-operator/cmd/kogito/command/deploy.(*deployCommand).Exec(0xc0001616c0, 0xc000108f00, 0x25d9c50, 0x0, 0x0, 0x0, 0x0)
	/data/dev/go_path/src/github.com/kiegroup/kogito-cloud-operator/cmd/kogito/command/deploy/deploy_service.go:158 +0x1299
github.com/spf13/cobra.(*Command).execute(0xc000108f00, 0x25d9c50, 0x0, 0x0, 0xc000108f00, 0x25d9c50)
	/data/dev/go_path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000108780, 0x43c337, 0x2549e00, 0x1d)
	/data/dev/go_path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/data/dev/go_path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.Main(0xc0008f1f20, 0x43c337)
	/data/dev/go_path/src/github.com/kiegroup/kogito-cloud-operator/cmd/kogito/main.go:26 +0x27
main.Execute()
	/data/dev/go_path/src/github.com/kiegroup/kogito-cloud-operator/cmd/kogito/main.go:32 +0x26
main.main()
	/data/dev/go_path/src/github.com/kiegroup/kogito-cloud-operator/cmd/kogito/main.go:39 +0x20
```

**Comment by Kevin-Mok** [comment]
Fixed by deploying the KogitoRuntime CRD to the cluster with `oc create -f deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml`.
